version: 2
updates:
- package-ecosystem: pip
  directory: "/src"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: faker
    versions:
    - 6.1.1
    - 6.4.1
    - 8.0.0
    - 8.1.0
  - dependency-name: asgiref
    versions:
    - 3.3.2
  - dependency-name: amqp
    versions:
    - 5.0.6
  - dependency-name: urllib3
    versions:
    - 1.26.4
  - dependency-name: coverage
    versions:
    - "5.5"
  - dependency-name: pygments
    versions:
    - 2.8.0
  - dependency-name: pytz
    versions:
    - "2021.1"
  - dependency-name: jedi
    versions:
    - 0.18.0
