# Generated by Django 3.1.5 on 2021-01-29 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='artist',
            options={'managed': True, 'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='track',
            options={'managed': True, 'ordering': ['id']},
        ),
    ]
