# Generated by Django 3.1.5 on 2021-01-29 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20210129_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(db_column='AlbumId', on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='music.album'),
        ),
    ]
