# Generated by Django 3.1.5 on 2021-01-31 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20210129_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistImage',
            fields=[
                ('id', models.AutoField(db_column='ArtistImageId', primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.OneToOneField(db_column='ArtistImageId', null=True, on_delete=django.db.models.deletion.CASCADE, to='music.artistimage'),
        ),
    ]
